In [37]:
import h5py as h5
import numpy as np

In [18]:
chris_data = np.genfromtxt('data/classifications/christopher_behrens.csv', delimiter=',', dtype=str)[1:]
chris = np.where(chris_data[:, 1] == 'single', 0, 1).reshape(-1, 1)

In [19]:
daniel_data = np.genfromtxt('data/classifications/daniel_ramm.csv', delimiter=',', dtype=str)[1:]
daniel = np.where(daniel_data[:, 1] == 'single', 0, 1).reshape(-1, 1)

In [20]:
jim_data = np.genfromtxt('data/classifications/jim_gerth.csv', delimiter=',', dtype=str)[1:]
jim = np.where(jim_data[:, 1] == 'single', 0, 1).reshape(-1, 1)

In [21]:
kai_data = np.genfromtxt('data/classifications/kai_tiedtke.csv', delimiter=',', dtype=str)[1:]
kai = np.where(kai_data[:, 1] == 'single', 0, 1).reshape(-1, 1)

In [22]:
evgyn_data = np.genfromtxt('data/classifications/Schneidmiller.csv', delimiter=',', dtype=str)[1:]
evgyn = np.where(evgyn_data[:, 1] == 'single', 0, 1).reshape(-1, 1)

In [31]:
data = np.concatenate((chris, daniel, jim, kai, evgyn), axis=1)

In [29]:
classifications = np.where(data.sum(axis=1) >= 3, 1, 0).reshape(-1, 1)

In [33]:
classifications

array([[1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
    

In [35]:
np.save('data/classifications.npy', classifications)

In [38]:
with h5.File('/Users/jim/PycharmProjects/pyqt_tinder-python/data/images_to_classify_manually.h5', 'r') as file:
    images = np.array(file['X_test'])

In [40]:
images.shape

(200, 100, 100)

In [41]:
images.reshape(200, 10000)

array([[ 1,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  1, ...,  1,  0,  1],
       ...,
       [ 0,  0,  0, ...,  0,  1,  0],
       [-1,  0,  0, ...,  0,  1,  1],
       [ 0,  1,  0, ...,  0, -1, -1]])

In [44]:
a = np.array([
    [[111, 121, 131],
     [112, 122, 132],
     [113, 123, 133]],
    
    [[211, 221, 231],
     [212, 222, 232],
     [213, 223, 233]],
    
    [[311, 321, 331],
     [312, 322, 332],
     [313, 323, 333]]
])
a.shape

(3, 3, 3)

In [45]:
a.reshape(3, 9)

array([[111, 121, 131, 112, 122, 132, 113, 123, 133],
       [211, 221, 231, 212, 222, 232, 213, 223, 233],
       [311, 321, 331, 312, 322, 332, 313, 323, 333]])